version: '3'

volumes:
  webapp:

services:

  # App
  app:
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: caddy_app
    restart: unless-stopped
    environment:
      - https_proxy
      - http_proxy
      - no_proxy
    volumes:
      - webapp:/var/www

  # Caddy
  web:
    build:
      context: ./web
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: caddy_web
    restart: unless-stopped
    environment:
      - https_proxy
      - http_proxy
      - no_proxy
    volumes:
      - webapp:/var/www:ro
    ports:
      - "8080:80"
    depends_on:
      - app
