version: '3'

volumes:
  webapp:

services:

  # App
  app:
    build:
      context: ./app
    container_name: caddy_app
    restart: unless-stopped
    volumes:
      - webapp:/var/www

  # Caddy
  web:
    build:
      context: ./web
    container_name: caddy_web
    restart: unless-stopped
    volumes:
      - webapp:/var/www:ro
    ports:
      - "8080:80"
    depends_on:
      - app
